---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: snryos
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/wayblueorg/hyprland
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
  
  - type: rpm-ostree
    replace:
      - from-repo: https://copr.fedorainfracloud.org/coprs/bazzite-org/bazzite/repo/fedora-%OS_VERSION%/bazzite-org-bazzite-fedora-%OS_VERSION%.repo
        packages:
          - linux-firmware
          - netronome-firmware
          - libertas-firmware
          - atheros-firmware
          - realtek-firmware
          - tiwilink-firmware
          - cirrus-audio-firmware
          - linux-firmware-whence
          - iwlwifi-dvm-firmware
          - iwlwifi-mvm-firmware
          - amd-ucode-firmware
          - qcom-firmware
          - mt7xxx-firmware
          - liquidio-firmware
          - nxpwireless-firmware
          - intel-vsc-firmware
          - nvidia-gpu-firmware
          - intel-audio-firmware
          - amd-gpu-firmware
          - iwlegacy-firmware
          - intel-gpu-firmware
          - mlxsw_spectrum-firmware
          - qed-firmware
          - mrvlprestera-firmware
          - brcmfmac-firmware
          - dvb-firmware

  - type: containerfile
    snippets:
      - |
        RUN --mount=type=cache,dst=/var/cache \
          --mount=type=cache,dst=/var/log \
          --mount=type=tmpfs,dst=/tmp \
          chmod +x /usr/bin/* && \
          dnf5 -y install dnf5-plugins && \
          for copr in \
              bazzite-org/bazzite \
              bazzite-org/bazzite-multilib \
              ublue-os/staging \
              ublue-os/packages \
              bazzite-org/LatencyFleX \
              bazzite-org/obs-vkcapture \
              bazzite-org/wallpaper-engine-kde-plugin \
              ycollet/audinux \
              bazzite-org/rom-properties \
              bazzite-org/webapp-manager \
              bazzite-org/vk_hdr_layer \
              hhd-dev/hhd \
              che/nerd-fonts \
              hikariknight/looking-glass-kvmfr \
              mavit/discover-overlay \
              lizardbyte/beta \
              rok/cdemu \
              rodoma92/kde-cdemu-manager \
              rodoma92/rmlint \
              ilyaz/LACT \
              tulilirockz/fw-fanctrl; \
          do \
              dnf5 -y copr enable $copr; \
              dnf5 -y config-manager setopt copr:copr.fedorainfracloud.org:${copr////:}.priority=98 ;\
          done && unset -v copr && \
          dnf5 -y install --nogpgcheck --repofrompath 'terra,https://repos.fyralabs.com/terra$releasever' terra-release{,-extras} && \
          dnf5 -y config-manager addrepo --overwrite --from-repofile=https://pkgs.tailscale.com/stable/fedora/tailscale.repo && \
          dnf5 -y install \
              https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
              https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm && \
          sed -i 's@enabled=0@enabled=1@g' /etc/yum.repos.d/negativo17-fedora-multimedia.repo && \
          dnf5 -y config-manager addrepo --from-repofile=https://negativo17.org/repos/fedora-steam.repo && \
          dnf5 -y config-manager addrepo --from-repofile=https://negativo17.org/repos/fedora-rar.repo && \
          dnf5 -y config-manager setopt "*bazzite*".priority=1 && \
          dnf5 -y config-manager setopt "*akmods*".priority=2 && \
          dnf5 -y config-manager setopt "*terra*".priority=3 "*terra*".exclude="nerd-fonts topgrade" && \
          dnf5 -y config-manager setopt "terra-mesa".enabled=true && \
          dnf5 -y config-manager setopt "terra-nvidia".enabled=false && \
          eval "$(/usr/bin/dnf5-setopt setopt '*negativo17*' priority=4 exclude='mesa-* *xone*')" && \
          dnf5 -y config-manager setopt "*rpmfusion*".priority=5 "*rpmfusion*".exclude="mesa-*" && \
          dnf5 -y config-manager setopt "*fedora*".exclude="mesa-* kernel-core-* kernel-modules-* kernel-uki-virt-*" && \
          dnf5 -y config-manager setopt "*staging*".exclude="scx-scheds kf6-* mesa* mutter* rpm-ostree* systemd* gnome-shell gnome-settings-daemon gnome-control-center gnome-software libadwaita tuned*" && \
          /usr/bin/cleanup
      - |
        RUN --mount=type=cache,dst=/var/cache \
          --mount=type=cache,dst=/var/log \
          --mount=type=tmpfs,dst=/tmp \
          declare -A toswap=( \
              ["copr:copr.fedorainfracloud.org:bazzite-org:bazzite-multilib"]="pipewire bluez xorg-x11-server-Xwayland" \
              ["terra-extras"]="switcheroo-control" \
              ["terra-mesa"]="mesa-filesystem" \
              ["copr:copr.fedorainfracloud.org:ublue-os:staging"]="fwupd" \
          ) && \
          for repo in "${!toswap[@]}"; do \
              for package in ${toswap[$repo]}; do dnf5 -y swap --repo=$repo $package $package; done; \
          done && unset -v toswap repo package && \
          dnf5 versionlock add \
              pipewire \
              pipewire-alsa \
              pipewire-gstreamer \
              pipewire-jack-audio-connection-kit \
              pipewire-jack-audio-connection-kit-libs \
              pipewire-libs \
              pipewire-plugin-libcamera \
              pipewire-pulseaudio \
              pipewire-utils \
              bluez \
              bluez-cups \
              bluez-libs \
              bluez-obexd \
              xorg-x11-server-Xwayland \
              switcheroo-control \
              mesa-dri-drivers \
              mesa-filesystem \
              mesa-libEGL \
              mesa-libGL \
              mesa-libgbm \
              mesa-va-drivers \
              mesa-vulkan-drivers \
              fwupd \
              fwupd-plugin-flashrom \
              fwupd-plugin-modem-manager \
              fwupd-plugin-uefi-capsule-data && \
          dnf5 -y install --enable-repo="*rpmfusion*" --disable-repo="*fedora-multimedia*" \
              libaacs \
              libbdplus \
              libbluray \
              libbluray-utils && \
          /usr/bin/cleanup
      - |
        RUN --mount=type=cache,dst=/var/cache \
            --mount=type=cache,dst=/var/log \
            --mount=type=tmpfs,dst=/tmp \
            dnf5 -y swap \
            --repo copr:copr.fedorainfracloud.org:bazzite-org:bazzite \
                ibus ibus && \
            dnf5 versionlock add \
                ibus && \
            dnf5 -y install \
                gamescope.x86_64 \
                gamescope-libs.x86_64 \
                gamescope-libs.i686 \
                gamescope-shaders \
                jupiter-sd-mounting-btrfs \
                umu-launcher \
                dbus-x11 \
                xdg-user-dirs \
                gobject-introspection \
                libFAudio.x86_64 \
                libFAudio.i686 \
                latencyflex-vulkan-layer \
                vkBasalt.x86_64 \
                vkBasalt.i686 \
                mangohud.x86_64 \
                mangohud.i686 \
                libobs_vkcapture.x86_64 \
                libobs_glcapture.x86_64 \
                libobs_vkcapture.i686 \
                libobs_glcapture.i686 \
                vk_hdr_layer.x86_64 \
                vk_hdr_layer.i686 && \
            dnf5 -y --setopt=install_weak_deps=False install \
                steam \
                lutris && \
            dnf5 -y remove \
                gamemode && \
            curl -Lo /tmp/latencyflex.tar.xz $(curl https://api.github.com/repos/ishitatsuyuki/LatencyFleX/releases/latest | jq -r '.assets[] | select(.name| test(".*.tar.xz$")).browser_download_url') && \
            mkdir -p /tmp/latencyflex && \
            tar --no-same-owner --no-same-permissions --no-overwrite-dir --strip-components 1 -xvf /tmp/latencyflex.tar.xz -C /tmp/latencyflex && \
            rm -f /tmp/latencyflex.tar.xz && \
            mkdir -p /usr/lib64/latencyflex && \
            cp -r /tmp/latencyflex/wine/usr/lib/wine/* /usr/lib64/latencyflex/ && \
            curl -Lo /usr/bin/latencyflex https://raw.githubusercontent.com/bazzite-org/LatencyFleX-Installer/main/install.sh && \
            chmod +x /usr/bin/latencyflex && \
            curl -Lo /usr/bin/winetricks https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks && \
            chmod +x /usr/bin/winetricks && \
            /usr/bin/cleanup

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/agriffis/neovim-nightly/repo/fedora-%OS_VERSION%/agriffis-neovim-nightly-fedora-%OS_VERSION%.repo
      - https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
      - https://copr.fedorainfracloud.org/coprs/sneexy/zen-browser/repo/fedora-%OS_VERSION%/sneexy-zen-browser-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/pgdev/ghostty/repo/fedora-%OS_VERSION%/pgdev-ghostty-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://negativo17.org/repos/fedora-rar.repo
    keys:
      - https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
    optfix:
      - brave.com
      - zen
    install:
      - rar
      - qt5ct
      - qt6ct
      - git
      - wlogout
      - mako
      - zsh
      - zsh-autosuggestions
      - zsh-syntax-highlighting
      - ghostty
      - starship
      - neovim
      - brave-browser
      - zen-browser
      - setroubleshoot
      - kate
      - kcalc
      - korganizer
      - system-config-printer
      - simple-scan
      - sane-airscan
      - libreoffice
      - kolourpaint
      - haruna
      - gwenview
      - xdg-desktop-portal-gtk
    remove:
      - firefox
      - firefox-langpacks
      - kitty

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - CascadiaCode
        - Iosevka
        - NerdFontsSymbolsOnly

  - type: script
    scripts:
      - setup-antidote.sh
      - ensure-executables.sh

  - type: systemd
    user:
      enabled:
        - nvim-config-setup.service

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      remove:
        - org.gnome.eog
    user: {} # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

