---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: snryos
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/wayblueorg/hyprland
image-version: latest

# FROM ghcr.io/ublue-os/akmods:${KERNEL_FLAVOR}-${FEDORA_MAJOR_VERSION}-${KERNEL_VERSION} AS akmods
# FROM ghcr.io/ublue-os/akmods-extra:${KERNEL_FLAVOR}-${FEDORA_MAJOR_VERSION}-${KERNEL_VERSION} AS akmods-extra

modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
        
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/agriffis/neovim-nightly/repo/fedora-%OS_VERSION%/agriffis-neovim-nightly-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/bazzite-org/bazzite/repo/fedora-%OS_VERSION%/bazzite-org-bazzite-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/bazzite-org/bazzite-multilib/repo/fedora-%OS_VERSION%/bazzite-org-bazzite-multilib-fedora-%OS_VERSION%.repo?arch=x86_64
    replace:
      - from-repo: https://copr.fedorainfracloud.org/coprs/bazzite-org/bazzite/repo/fedora-%OS_VERSION%/bazzite-org-bazzite-fedora-%OS_VERSION%.repo
        packages:
          - linux-firmware
          - netronome-firmware
          - libertas-firmware
          - atheros-firmware
          - realtek-firmware
          - tiwilink-firmware
          - cirrus-audio-firmware
          - linux-firmware-whence
          - iwlwifi-dvm-firmware
          - iwlwifi-mvm-firmware
          - amd-ucode-firmware
          - qcom-firmware
          - mt7xxx-firmware
          - liquidio-firmware
          - nxpwireless-firmware
          - intel-vsc-firmware
          - nvidia-gpu-firmware
          - intel-audio-firmware
          - amd-gpu-firmware
          - iwlegacy-firmware
          - intel-gpu-firmware
          - mlxsw_spectrum-firmware
          - qed-firmware
          - mrvlprestera-firmware
          - brcmfmac-firmware
          - dvb-firmware
      - from-repo: https://copr.fedorainfracloud.org/coprs/bazzite-org/bazzite-multilib/repo/fedora-%OS_VERSION%/bazzite-org-bazzite-multilib-fedora-%OS_VERSION%.repo?arch=x86_64
        packages:
          - pipewire
          - pipewire-libs
          - pipewire-jack-audio-connection-kit
          - pipewire-jack-audio-connection-kit-libs
          - pipewire-plugin-libcamera
          - pipewire-gstreamer
          - pipewire-utils
          - pipewire-alsa
          - pipewire-pulseaudio
      - from-repo: https://copr.fedorainfracloud.org/coprs/bazzite-org/bazzite-multilib/repo/fedora-%OS_VERSION%/bazzite-org-bazzite-multilib-fedora-%OS_VERSION%.repo?arch=x86_64
        packages:
          - pipewire
          - pipewire-libs
          - pipewire-jack-audio-connection-kit
          - pipewire-jack-audio-connection-kit-libs
          - pipewire-plugin-libcamera
          - pipewire-gstreamer
          - pipewire-utils
          - pipewire-alsa
          - pipewire-pulseaudio
      - from-repo: https://raw.githubusercontent.com/terrapkg/packages/refs/heads/frawhide/anda/terra/release/terra-mesa.repo
        packages:
          - mesa-dri-drivers
          - mesa-filesystem
          - mesa-libEGL
          - mesa-libGL
          - mesa-libgbm
          - mesa-va-drivers
          - mesa-vulkan-drivers

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/sneexy/zen-browser/repo/fedora-%OS_VERSION%/sneexy-zen-browser-fedora-%OS_VERSION%.repo
      - https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
      - https://raw.githubusercontent.com/terrapkg/packages/refs/heads/frawhide/anda/terra/release/terra.repo
      - https://raw.githubusercontent.com/terrapkg/packages/refs/heads/frawhide/anda/terra/release/terra-extras.repo
    keys:
      - https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
    optfix:
      - brave.com
    install:
      - git
      - wlogout
      - mako
      - zsh
      - zsh-autosuggestions
      - zsh-syntax-highlighting
      - ghostty
      - starship
      - neovim
      - brave-browser
      - zen-browser
      - setroubleshoot
      - kate
      - kcalc
      - korganizer
      - system-config-printer
      - simple-scan
      - sane-airscan
      - libreoffice
      - kolourpaint
      - haruna
      - gwenview
      - xdg-desktop-portal-gtk
    remove:
      - firefox
      - firefox-langpacks
      - kitty

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - CascadiaCode
        - Iosevka
        - NerdFontsSymbolsOnly

  - type: script
    scripts:
      - setup-antidote.sh
      - ensure-executables.sh

  - type: systemd
    user:
      enabled:
        - nvim-config-setup.service

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      remove:
        - org.gnome.eog
    user: {} # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

