---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: snryos
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/wayblueorg/hyprland
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
  
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/bazzite-org/bazzite/repo/fedora-%OS_VERSION%/bazzite-org-bazzite-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/bazzite-org/bazzite-multilib/repo/fedora-%OS_VERSION%/bazzite-org-bazzite-multilib-fedora-%OS_VERSION%.repo?arch=x86_64
    replace:
      - from-repo: https://copr.fedorainfracloud.org/coprs/bazzite-org/bazzite/repo/fedora-%OS_VERSION%/bazzite-org-bazzite-fedora-%OS_VERSION%.repo
        packages:
          - linux-firmware
          - netronome-firmware
          - libertas-firmware
          - atheros-firmware
          - realtek-firmware
          - tiwilink-firmware
          - cirrus-audio-firmware
          - linux-firmware-whence
          - iwlwifi-dvm-firmware
          - iwlwifi-mvm-firmware
          - amd-ucode-firmware
          - qcom-firmware
          - mt7xxx-firmware
          - liquidio-firmware
          - nxpwireless-firmware
          - intel-vsc-firmware
          - nvidia-gpu-firmware
          - intel-audio-firmware
          - amd-gpu-firmware
          - iwlegacy-firmware
          - intel-gpu-firmware
          - mlxsw_spectrum-firmware
          - qed-firmware
          - mrvlprestera-firmware
          - brcmfmac-firmware
          - dvb-firmware
      - from-repo: https://copr.fedorainfracloud.org/coprs/bazzite-org/bazzite-multilib/repo/fedora-%OS_VERSION%/bazzite-org-bazzite-multilib-fedora-%OS_VERSION%.repo?arch=x86_64
        packages:
          - pipewire
          - pipewire-libs
          - pipewire-jack-audio-connection-kit
          - pipewire-jack-audio-connection-kit-libs
          - pipewire-plugin-libcamera
          - pipewire-gstreamer
          - pipewire-utils
          - pipewire-alsa
          - pipewire-pulseaudio
    install:
      - gamescope.x86_64
      - gamescope-libs.x86_64
      - gamescope-libs.i686
      - gamescope-shaders
      - umu-launcher
      - dbus-x11
      - xdg-user-dirs
      - gobject-introspection
      - libFAudio.x86_64
      - libFAudio.i686
      - vkBasalt.x86_64
      - vkBasalt.i686

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/agriffis/neovim-nightly/repo/fedora-%OS_VERSION%/agriffis-neovim-nightly-fedora-%OS_VERSION%.repo
      - https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
      - https://copr.fedorainfracloud.org/coprs/sneexy/zen-browser/repo/fedora-%OS_VERSION%/sneexy-zen-browser-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/pgdev/ghostty/repo/fedora-%OS_VERSION%/pgdev-ghostty-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://negativo17.org/repos/fedora-rar.repo
    keys:
      - https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
    optfix:
      - brave.com
      - zen
    install:
      - rar
      - qt5ct
      - qt6ct
      - git
      - wlogout
      - mako
      - zsh
      - zsh-autosuggestions
      - zsh-syntax-highlighting
      - ghostty
      - starship
      - neovim
      - brave-browser
      - zen-browser
      - setroubleshoot
      - kate
      - kcalc
      - korganizer
      - system-config-printer
      - simple-scan
      - sane-airscan
      - libreoffice
      - kolourpaint
      - haruna
      - gwenview
      - xdg-desktop-portal-gtk
    remove:
      - firefox
      - firefox-langpacks
      - kitty

  - type: containerfile
    snippets:
      - |
        RUN --mount=type=cache,dst=/var/cache \
          --mount=type=cache,dst=/var/log \
          --mount=type=tmpfs,dst=/tmp \
          dnf5 -y --setopt=install_weak_deps=False install \
              steam \
              lutris && \
          dnf5 -y remove \
              gamemode && \
          curl -Lo /usr/bin/winetricks https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks && \
          chmod +x /usr/bin/winetricks

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - CascadiaCode
        - Iosevka
        - NerdFontsSymbolsOnly

  - type: script
    scripts:
      - setup-antidote.sh
      - ensure-executables.sh

  - type: systemd
    user:
      enabled:
        - nvim-config-setup.service

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      remove:
        - org.gnome.eog
    user: {} # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

